## Please run npm i --package-lock-only to generate lock file before start
services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "8080:80"
    networks:
       myapp-net:
          aliases:
             - frontend

  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    networks:
       myapp-net:
          aliases:
             - backend

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.35.0
    volumes:
      - prometheus_data:/prometheus
      - .prom_files/prometheus.yml:/etc/prometheus/prometheus.yml
      - .prom_files/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
       myapp-net:

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.3.1
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
       myapp-net:

# https://grafana.com/grafana/dashboards/16306-express-prometheus-middleware/
# https://grafana.com/grafana/dashboards/11956-nodejs-metrics/

  grafana:
    container_name: grafana
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
       myapp-net:

networks:
  myapp-net:
     name: myapp-net
     
volumes:
    prometheus_data: {}
    grafana_data: {}